version: "3.3"

services: 

  dbase:
    image: mariadb
    container_name: dbase
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financiera
      MYSQL_USER: hugocanul
      MYSQL_PASSWORD: ha260182ha
    restart: always
    ports:
      - 6033:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadphp2
    depends_on:
      - dbase
    environment:
      PMA_HOST: dbase
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 9001:80


  api:
    build:
      context: ./backend
    container_name: api
    ports: 
      - 9002:7570
    depends_on: 
      - dbase
    volumes:
      - ./code/backend:/root/api-rest


  vuejs:
    build: 
      context: ./frontend
    ports:
      - 9003:8080
    depends_on: 
      - api
    volumes: 
      - ./code/frontend:/root/frontend


  vscode:
    build: 
      context: ./vscode
    ports:
      - 9004:8080
    depends_on: 
      - api
      - vuejs
    volumes: 
      - ./code:/root/projects



